### ISSUE TITLE
[Child of #1773] Update Storybook to version 6 [Due Date: 03.08.20]

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1774]
We dont want to redesign storybook on a old version to avoid doubled work. The updated causes some breaking changes and we want to fix them first.

**Comment by danyball** [comment]
Something not working with 5.3 internally:

```
TypeError: Invalid attempt to spread non-iterable instance
   at _nonIterableSpread (http://localhost:6006/vendors~main.133d19674bf184295530.bundle.js:14402:33)
   at _toConsumableArray (http://localhost:6006/vendors~main.133d19674bf184295530.bundle.js:14400:36)
   at Anonymous function (http://localhost:6006/vendors~main.133d19674bf184295530.bundle.js:14858:7)
   at render (http://localhost:6006/vendors~main.133d19674bf184295530.bundle.js:11859:13)
   at configure (http://localhost:6006/vendors~main.133d19674bf184295530.bundle.js:11894:9)
   at configure (http://localhost:6006/vendors~main.133d19674bf184295530.bundle.js:14983:5)
   at configure (http://localhost:6006/vendors~main.133d19674bf184295530.bundle.js:24887:3)
   at Anonymous function (http://localhost:6006/main.133d19674bf184295530.bundle.js:246:1)
   at ./.storybook/generated-entry.js (http://localhost:6006/main.133d19674bf184295530.bundle.js:242:29)
   at __webpack_require__ (http://localhost:6006/runtime~main.133d19674bf184295530.bundle.js:849:12)

```

generated-entry.js:
```
import { configure } from '@storybook/html';
              module._StorybookPreserveDecorators = true;

              configure([require.context('../src/components', true, /^\.\/(?:(?:|\/|(?:(?:(?!(?:|\/)\.).)*?)\/)story\.js)$/)
              ], module);
```

--> `configure` could be the problem internally?!

Next step: Try updating to SB 6 Beta

**Comment by danyball** [comment]
Because of successful upgrading to SB 6.X RC we are waiting till the 6 final release. A good starting point to upgrade is this branch: `feature/update-storybook-5-3`. 

Due date to upgrade: https://github.com/storybookjs/storybook/issues/9311

**Comment by raphael-suter** [comment]
Please have a look at #1898 after the update.

**Comment by danyball** [comment]
WARN Found 5 outdated packages (relative to '@storybook/channels@6.0.12')
WARN Please make sure your packages are updated to ensure a consistent experience.
WARN - @storybook/components@5.3.19
WARN - @storybook/client-logger@5.3.19
WARN - @storybook/theming@5.3.19
WARN - @storybook/client-logger@5.3.19
WARN - @storybook/core-events@5.3.19
