### ISSUE TITLE
AXAFieldset/Jest/JSDom: Converting circular structure to JSON

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#2233]
Hi!

Probably this is a Jest/JSDom issue (or Lit-Element, or React issue), and not a PL issue, as its implementation of AXAFieldset is very minimalistic.

Anyway maybe you can give a hint why this error occurs.

Thanks!

This happens under Jest/JSDom env:

```
import createAXAFieldset from '@axa-ch/fieldset/lib/index.react';
import * as React from 'react';
const AXAFieldset = createAXAFieldset(React.createElement);
...

// works normally, no errors:
    <AXAFieldset>
      a
     </AXAFieldset>

// throws error
    <AXAFieldset>
      <span/>
     </AXAFieldset>
```

Versions:

Jest: 27.3.1
JSDom: 16.7.0
axa-fieldset: 4.1.12
lit-element: 2.5.1

Log:
```
Error: Uncaught [TypeError: Converting circular structure to JSON
--> starting at object with constructor 'Object'
|     property '_context' -> object with constructor 'Object'
--- property 'Provider' closes the circle]
at reportException (C:\***\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:66:24)
at innerInvokeEventListeners (C:\***\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:341:9)
at invokeEventListeners (C:\***\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:274:3)
at HTMLUnknownElementImpl._dispatch (C:\***\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:221:9)
at HTMLUnknownElementImpl.dispatchEvent (C:\***\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:94:17)
at HTMLUnknownElement.dispatchEvent (C:\***\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:231:34)
at Object.invokeGuardedCallbackDev (C:\***\node_modules\react-dom\cjs\react-dom.development.js:237:16)
at invokeGuardedCallback (C:\***\node_modules\react-dom\cjs\react-dom.development.js:292:31)
at beginWork$1 (C:\***\node_modules\react-dom\cjs\react-dom.development.js:23203:7)
at performUnitOfWork (C:\***\node_modules\react-dom\cjs\react-dom.development.js:22157:12) TypeError: Converting circular structure to JSON
--> starting at object with constructor 'Object'
|     property '_context' -> object with constructor 'Object'
--- property 'Provider' closes the circle
at JSON.stringify (<anonymous>)
at C:\***\.jest\plReactComponentMock.ts:15:72
at renderWithHooks (C:\***\node_modules\react-dom\cjs\react-dom.development.js:14803:18)
at mountIndeterminateComponent (C:\***\node_modules\react-dom\cjs\react-dom.development.js:17482:13)
at beginWork (C:\***\node_modules\react-dom\cjs\react-dom.development.js:18596:16)
at HTMLUnknownElement.callCallback (C:\***\node_modules\react-dom\cjs\react-dom.development.js:188:14)
at HTMLUnknownElement.callTheUserObjectsOperation (C:\***\node_modules\jsdom\lib\jsdom\living\generated\EventListener.js:26:30)
at innerInvokeEventListeners (C:\***\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:338:25)
at invokeEventListeners (C:\***\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:274:3)
at HTMLUnknownElementImpl._dispatch (C:\***\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:221:9)
at HTMLUnknownElementImpl.dispatchEvent (C:\***\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:94:17)
at HTMLUnknownElement.dispatchEvent (C:\***\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:231:34)
at Object.invokeGuardedCallbackDev (C:\***\node_modules\react-dom\cjs\react-dom.development.js:237:16)
at invokeGuardedCallback (C:\***\node_modules\react-dom\cjs\react-dom.development.js:292:31)
at beginWork$1 (C:\***\node_modules\react-dom\cjs\react-dom.development.js:23203:7)
at performUnitOfWork (C:\***\node_modules\react-dom\cjs\react-dom.development.js:22157:12)
at workLoopSync (C:\***\node_modules\react-dom\cjs\react-dom.development.js:22130:22)
at performSyncWorkOnRoot (C:\***\node_modules\react-dom\cjs\react-dom.development.js:21756:9)
at scheduleUpdateOnFiber (C:\***\node_modules\react-dom\cjs\react-dom.development.js:21188:7)
at updateContainer (C:\***\node_modules\react-dom\cjs\react-dom.development.js:24373:3)
at C:\***\node_modules\react-dom\cjs\react-dom.development.js:24758:7
at unbatchedUpdates (C:\***\node_modules\react-dom\cjs\react-dom.development.js:21903:12)
at legacyRenderSubtreeIntoContainer (C:\***\node_modules\react-dom\cjs\react-dom.development.js:24757:5)
at Object.render (C:\***\node_modules\react-dom\cjs\react-dom.development.js:24840:10)
at PodMyaxaCompanyRegistration.init (C:\***\src\index.ts:40:16)
at new PodMyaxaCompanyRegistration (C:\***\src\index.ts:35:10)
at Object.<anonymous> (C:\***\src\pod.test.ts:62:17)
at Object.asyncJestTest (C:\***\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:106:37)
at C:\***\node_modules\jest-jasmine2\build\queueRunner.js:45:12
at new Promise (<anonymous>)
at mapper (C:\***\node_modules\jest-jasmine2\build\queueRunner.js:28:19)
at C:\***\node_modules\jest-jasmine2\build\queueRunner.js:75:41
at processTicksAndRejections (internal/process/task_queues.js:97:5)

at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:341:9)
at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
```

**Comment by MKaHead** [comment]
If the problem is urgent, we offer support. However, we have decided not to change anything in the production code.
