### ISSUE TITLE
Edit _abstract/index.js stops build

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#336]
## Are you reporting a bug or a feature?

 - [x] Bug

## Expected Behavior

Editing `_abstact/index.js` should just rebuild.

## Actual Behavior

The build stops working.

```sh
(node:6999) UnhandledPromiseRejectionWarning: Error: Could not resolve entry (/Users/axawinterthur/dev/axa-ch_style-html-guide/src/components/_abstract/index.js)
    at error (/Users/axawinterthur/dev/axa-ch_style-html-guide/node_modules/rollup/dist/rollup.js:168:15)
    at /Users/axawinterthur/dev/axa-ch_style-html-guide/node_modules/rollup/dist/rollup.js:21170:17
    at <anonymous>
(node:6999) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6999) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Steps to Reproduce the Problem

1. run `npm run serve`
2. edit `_abstract/index.js`

**Comment by AndyOGo** [comment]
btw I think it could make sense to move `_abstract/index.js` to `src/js/base-component`

**Comment by LucaMele** [comment]
i agree...

**Comment by LucaMele** [comment]
dafuq it DOES NOT REBUILD?? shit this is a bug that must have sneaked in when i did the performance rework for the build

**Comment by AndyOGo** [comment]
🤔

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
