### ISSUE TITLE
Module build failed: Error: Unknown plugin "external-helpers"

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#54]
I'm currently migrating the footer in axa.ch repo and face this bug.
So I just installed it locally into the aem repo, though we should document this some how.

> ERROR in ./~/@axa-ch/patterns-library/src/components/m-footer-links/js/footer-links.js
[scripts:watch] Module build failed: Error: Unknown plugin "external-helpers" specified in "/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/@axa-ch/patterns-library/.babelrc" at 0, attempted to resolve relative to "/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/@axa-ch/patterns-library"
[scripts:watch] ReferenceError: Unknown plugin "external-helpers" specified in "/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/@axa-ch/patterns-library/.babelrc" at 0, attempted to resolve relative to "/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/@axa-ch/patterns-library"
[scripts:watch]     at /Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
[scripts:watch]     at Array.map (native)
[scripts:watch]     at Function.normalisePlugins (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
[scripts:watch]     at OptionManager.mergeOptions (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
[scripts:watch]     at OptionManager.init (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
[scripts:watch]     at File.initOptions (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-core/lib/transformation/file/index.js:216:65)
[scripts:watch]     at new File (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-core/lib/transformation/file/index.js:139:24)
[scripts:watch]     at Pipeline.transform (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
[scripts:watch]     at transpile (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-loader/lib/index.js:46:20)
[scripts:watch]     at /Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-loader/lib/fs-cache.js:79:18
[scripts:watch]     at /Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/happypack/lib/HappyLoader.js:46:23
[scripts:watch]     at Object.Thread::0:1 (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/happypack/lib/HappyPlugin.js:321:7)
[scripts:watch]     at ChildProcess.acceptMessageFromWorker (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/happypack/lib/HappyThread.js:66:32)
[scripts:watch]     at emitTwo (events.js:105:20)
[scripts:watch]     at ChildProcess.emit (events.js:185:7)
[scripts:watch]     at handleMessage (internal/child_process.js:718:10)
[scripts:watch]     at Pipe.channel.onread (internal/child_process.js:444:11)
[scripts:watch]  @ ./src/js/redesign/footer-links.binding.js 7:19-100
[scripts:watch]

> [scripts:watch] ERROR in ./~/@axa-ch/patterns-library/src/components/a-device-state/js/device-state.js
[scripts:watch] Module build failed: Error: Unknown plugin "external-helpers" specified in "/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/@axa-ch/patterns-library/.babelrc" at 0, attempted to resolve relative to "/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/@axa-ch/patterns-library"
[scripts:watch] ReferenceError: Unknown plugin "external-helpers" specified in "/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/@axa-ch/patterns-library/.babelrc" at 0, attempted to resolve relative to "/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/@axa-ch/patterns-library"
[scripts:watch]     at /Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
[scripts:watch]     at Array.map (native)
[scripts:watch]     at Function.normalisePlugins (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
[scripts:watch]     at OptionManager.mergeOptions (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
[scripts:watch]     at OptionManager.init (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
[scripts:watch]     at File.initOptions (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-core/lib/transformation/file/index.js:216:65)
[scripts:watch]     at new File (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-core/lib/transformation/file/index.js:139:24)
[scripts:watch]     at Pipeline.transform (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
[scripts:watch]     at transpile (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-loader/lib/index.js:46:20)
[scripts:watch]     at /Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-loader/lib/fs-cache.js:79:18
[scripts:watch]     at /Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/happypack/lib/HappyLoader.js:46:23
[scripts:watch]     at Object.Thread::1:1 (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/happypack/lib/HappyPlugin.js:321:7)
[scripts:watch]     at ChildProcess.acceptMessageFromWorker (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/happypack/lib/HappyThread.js:66:32)
[scripts:watch]     at emitTwo (events.js:105:20)
[scripts:watch]     at ChildProcess.emit (events.js:185:7)
[scripts:watch]     at handleMessage (internal/child_process.js:718:10)
[scripts:watch]     at Pipe.channel.onread (internal/child_process.js:444:11)
[scripts:watch]  @ ./src/js/redesign/device-state.binding.js 7:19-100

**Comment by AndyOGo** [comment]
Guess the same:

> [ReferenceError: Unknown plugin "transform-custom-element-classes" specified in "/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/@axa-ch/patterns-library/.babelrc" at 1, attempted to resolve relative to "/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/@axa-ch/patterns-library"]

**Comment by AndyOGo** [comment]
> Module build failed: Error: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

> ERROR in ./~/@axa-ch/patterns-library/src/components/m-footer-links/js/footer-links.js
[scripts:watch] Module build failed: Error: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
[scripts:watch] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
[scripts:watch]     at exports.runInThisContext (vm.js:53:16)
[scripts:watch]     at Module._compile (module.js:387:25)
[scripts:watch]     at Object.Module._extensions..js (module.js:422:10)
[scripts:watch]     at Module.load (module.js:357:32)
[scripts:watch]     at Function.Module._load (module.js:314:12)
[scripts:watch]     at Module.require (module.js:367:17)
[scripts:watch]     at require (internal/module.js:20:19)
[scripts:watch]     at /Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:178:20
[scripts:watch]     at Array.map (native)
[scripts:watch]     at Function.normalisePlugins (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
[scripts:watch]     at /Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/happypack/lib/HappyLoader.js:46:23
[scripts:watch]     at Object.Thread::0:1 (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/happypack/lib/HappyPlugin.js:321:7)
[scripts:watch]     at ChildProcess.acceptMessageFromWorker (/Users/axawinterthur/dev/aem-all_ext/frontend-lib/node_modules/happypack/lib/HappyThread.js:66:32)
[scripts:watch]     at emitTwo (events.js:105:20)
[scripts:watch]     at ChildProcess.emit (events.js:185:7)
[scripts:watch]     at handleMessage (internal/child_process.js:718:10)
[scripts:watch]     at Pipe.channel.onread (internal/child_process.js:444:11)
[scripts:watch]  @ ./src/js/redesign/footer-links.binding.js 7:19-100

**Comment by AndyOGo** [comment]
related bug:
https://github.com/github/babel-plugin-transform-custom-element-classes/issues/9

**Comment by AndyOGo** [comment]
`babel-plugin-transform-custom-element-classes` seems not to be maintained, I guess we should fork it, to fix that bug by ourselves...

**Comment by AndyOGo** [comment]
Quick fix, pump node version to more that `4.x, 5.x`.
`6.10.2` worked for me

**Comment by AndyOGo** [comment]
@LucaMele 
I would see we should add a warning block to the readme including this culprit and the solution with newer node version, then closing this...
