### ISSUE TITLE
can't omit default export

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#609]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

I expect to have JS file only using named exports to be build successfully.

## Actual Behavior

JS files with just named exports i.e. without `export default` break the build.

## Failure Logs

```sh
(node:22600) UnhandledPromiseRejectionWarning: Error: 'default' is not exported by src/js/prop-types/table-prop-types.js
[2]     at error (/Users/axawinterthur/dev/axa-ch_style-html-guide/node_modules/rollup/dist/rollup.js:170:15)
[2]     at Module.error (/Users/axawinterthur/dev/axa-ch_style-html-guide/node_modules/rollup/dist/rollup.js:17195:9)
[2]     at handleMissingExport (/Users/axawinterthur/dev/axa-ch_style-html-guide/node_modules/rollup/dist/rollup.js:17458:12)
[2]     at /Users/axawinterthur/dev/axa-ch_style-html-guide/node_modules/rollup/dist/rollup.js:19031:56
[2]     at Array.reduce (<anonymous>)
[2]     at Graph.handleMissingExport (/Users/axawinterthur/dev/axa-ch_style-html-guide/node_modules/rollup/dist/rollup.js:19030:27)
[2]     at Module.trace (/Users/axawinterthur/dev/axa-ch_style-html-guide/node_modules/rollup/dist/rollup.js:17292:28)
[2]     at ModuleScope.findVariable (/Users/axawinterthur/dev/axa-ch_style-html-guide/node_modules/rollup/dist/rollup.js:14431:28)
[2]     at Node.Identifier.bindNode (/Users/axawinterthur/dev/axa-ch_style-html-guide/node_modules/rollup/dist/rollup.js:12115:40)
[2]     at NodeBase.bind (/Users/axawinterthur/dev/axa-ch_style-html-guide/node_modules/rollup/dist/rollup.js:11072:14)
[2] (node:22600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[2] (node:22600) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open
